/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EsqueciASenhaRouteImport } from './routes/esqueci-a-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedEnviarArquivosRouteImport } from './routes/_authenticated/enviar-arquivos'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciASenhaRoute = EsqueciASenhaRouteImport.update({
  id: '/esqueci-a-senha',
  path: '/esqueci-a-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEnviarArquivosRoute =
  AuthenticatedEnviarArquivosRouteImport.update({
    id: '/_authenticated/enviar-arquivos',
    path: '/enviar-arquivos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/_authenticated/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/login': typeof LoginRoute
  '/enviar-arquivos': typeof AuthenticatedEnviarArquivosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/login': typeof LoginRoute
  '/enviar-arquivos': typeof AuthenticatedEnviarArquivosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-a-senha': typeof EsqueciASenhaRoute
  '/login': typeof LoginRoute
  '/_authenticated/enviar-arquivos': typeof AuthenticatedEnviarArquivosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/esqueci-a-senha'
    | '/login'
    | '/enviar-arquivos'
    | '/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/esqueci-a-senha'
    | '/login'
    | '/enviar-arquivos'
    | '/historico'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/esqueci-a-senha'
    | '/login'
    | '/_authenticated/enviar-arquivos'
    | '/_authenticated/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  EsqueciASenhaRoute: typeof EsqueciASenhaRoute
  LoginRoute: typeof LoginRoute
  AuthenticatedEnviarArquivosRoute: typeof AuthenticatedEnviarArquivosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-a-senha': {
      id: '/esqueci-a-senha'
      path: '/esqueci-a-senha'
      fullPath: '/esqueci-a-senha'
      preLoaderRoute: typeof EsqueciASenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/enviar-arquivos': {
      id: '/_authenticated/enviar-arquivos'
      path: '/enviar-arquivos'
      fullPath: '/enviar-arquivos'
      preLoaderRoute: typeof AuthenticatedEnviarArquivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  EsqueciASenhaRoute: EsqueciASenhaRoute,
  LoginRoute: LoginRoute,
  AuthenticatedEnviarArquivosRoute: AuthenticatedEnviarArquivosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
